### ISSUE TITLE
0.9.4 library is no longer available on the Arduino IDE.

### ISSUE THREAD

**Issue by SalamanderAnder** [Roboxtools/ArtKeyboard#1]
I'm new to all this. I'm getting the NRF52 set up now but I noticed on your known issues you said this code only works with the 0.9.4 library. Only problem is that the 0.9.4 library is not an option in the boards manager. It jumps from 0.9.3 to 0.10.1. Do you have any ideas?

Edit: Nevermind, I'm dumb. I just read the comment in your code to install 0.9.3. that seems to have worked.

**Comment by Roboxtools** [comment]
you also can use 0.9.3
